name = "file-manager-frontend"
main = "src/index.js"
account_id = "9debd4f6eee43dbbbbaf116d20f8ea01"
compatibility_date = "2025-12-17"
compatibility_flags = ["nodejs_compat"]

# Build configuration
build = { command = "npm run build", cwd = "./frontend" }

# Environment-specific configuration
[env.production]
routes = [
  { pattern = "drive.itc-group.co.th/*", zone_name = "itc-group.co.th" }
]
vars = { API_URL = "http://driveback.itc-group.co.th:2087" }
kv_namespaces = [
  { binding = "drive_manager", id = "9004cee6560447a9874cb30009088cac", preview_id = "9004cee6560447a9874cb30009088cac" }
]

[env.development]
vars = { API_URL = "http://localhost:2087" }
kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "cee2f7b346f14223814f83af66ca22f6", preview_id = "cee2f7b346f14223814f83af66ca22f6" }
]

